In [10]:
import numpy as np

## Numpy Arrays 

Los arrays de Numpy permiten acceder de manera mucho más óptima (al estar diseñados en C) a contenidos de datos. Además, existen una gran cantidad de operaciones aritméticas y estadísticas `in-built`.

In [11]:
arr = [1,2,3,4,5]
print(f"{arr} --- Type: {type(arr)}")

numpy_arr = np.array(arr)
print(f"{numpy_arr} --- Type: {type(numpy_arr)}")

[1, 2, 3, 4, 5] --- Type: <class 'list'>
[1 2 3 4 5] --- Type: <class 'numpy.ndarray'>


## Dimensiones en Numpy

Numpy permite hacer arrays nestados (al igual que en Python Vanilla), permitiendo crear arrays $n$-dimensionales. ¿Cómo se hace esto?

In [12]:
arr = np.array(42) # 0-Dimensional
print(arr, arr.shape, arr.ndim, "\n")

arr = np.array([1, 2, 3, 4, 5]) # 1-Dimensional
print(arr, arr.shape, arr.ndim, "\n")

arr = np.array([[1,2,3], [4,5,6]]) # 2-Dimensional
print(arr, arr.shape, arr.ndim, "\n") # obtenemos una matriz de tamaño 2 columnas x 3 filas

42 () 0 

[1 2 3 4 5] (5,) 1 

[[1 2 3]
 [4 5 6]] (2, 3) 2 



Podemos forzar la dimensionalidad de un array tal que:

In [13]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


## Reshape en Numpy

Un numpy array tiene el atributo `.shape`, que nos permite visualizar la forma del array. Pero ¿y si queremos modificar dicha forma (ya sea para usarlo en Tensores (Machine Learning) u por motivos diversos)?

In [90]:
from numpy import random

arr=random.randint(10, size=(12))
print(x)

newarr = arr.reshape(4, 3)
print(newarr) 
# muy útil para convertir 1-D en matrices o tensores!

[9 4 1 7 3 8 6 2 3 0 5 6]
[[2 6 3]
 [7 2 5]
 [8 7 2]
 [9 4 3]]


**¿Podemos hacer reshape siempre?** -> NO

Solo podemos hacer reshape cuando el tamaño total del array original permita tener en el nuevo array el mismo número de elementos en cada parte.

In [93]:
try:
    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # ocho elementos
    newarr = arr.reshape(3, 3) # necesitamos nueve elementos
    print(newarr)
except Exception as e:
    print(f"=== error === {e}")

=== error === cannot reshape array of size 8 into shape (3,3)


## Acceder a los elementos del array

Al igual que en Python Vanilla, tenemos la posibilidad de acceder a los elementos que conforman un array usando los índices en los que están dispuestos.

En la programación, **el primer índice suele ser el `0`**.

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(0, 10, 1): # empezamos en cero, acabamos en la pos 9
    print(arr[i]) # imprime el valor de dicha posición

1
2
3
4
5
6
7
8
9
10


In [15]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3]) # devuelve la suma de los elementos en las posiciones 2 y 3

7


### Acceder a arrays $n$-dimensionales

In [9]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.shape) 
print(arr[0, 1, 2]) # first element, second element, third element

(2, 2, 3)
6


## Array Slicing

Esto significa seleccionar, en un array, una serie de elementos.

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) # del elemento en la segunda posición hasta la sexta

[2 3 4 5]


¿Cómo podemos imprimir desde la tercera posición hasta la última?

In [21]:
print(arr[3:])

[4 5 6 7]


¿Y desde la primera hasta la segunda posición? 

In [24]:
print(arr[:3]) # hasta el índice 3, pero no cuenta

[1 2 3]


Hemos iterado de izquierda a derecha desde el principio del array (posición 0). ¿Pero y si quiero empezar desde el final?

In [26]:
print(arr[-3:-1]) # from the index 3 from the end to index 1 from the end

[5 6]


$n-dimensional$ Array Slicing

In [36]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 0:3]) # primer elemento, dentro del primer elemento los tres primeros indices

[1 2 3]


Esto es aplicable a arrays de dimensión $n$. Debemos de poner tantos índices como dimensiones tenga el array (y queramos trabajar con ellas)

### Steps

El equivalente del `for i in range(0, len(arr), 1)` en Python Vanilla, pero con una sintaxis mucho más cómoda.

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) # desde la pos1 hasta la pos5, de 2 en 2 -> pos1 -> pos3 -> pos5 (no se cuenta)

[2 4]


¿Y qué pasa si en vez de 2 usamos -2?

In [32]:
print(arr[5:1:-1]) # desde la pos 5 hasta la pos1 (no cuenta), de -1 en -1

[6 5 4 3]


## Iterar por el array

Un numpy array no es tan diferente de un array de Python Vanilla. Si iteramos a través de él, solamente profundizaremos en su dimensión menos profunda.

In [96]:
arr = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x) 

for x in arr2:
  print(x) 

1
2
3
[1 2 3]
[4 5 6]


¿Y si queremos iterar en una mayor profundidad?

In [97]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


Esto sigue la estructura común de un array en Python Vanilla. Es decir, recorremos todos los elementos (pos 0 y pos1). Para cada elemento, recorrer todos los elementos que se encuentran dentro de dicho array.

## Tipos de Datos - Numpy

Heredan de los tipos de Python, pero **NO SON** tipos de Python. Entre ellos podemos encontrar los siguientes:

- strings - S
- integer - i 
- float - f
- boolean
- complex

In [53]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5.0, 6.0])
arr3 = np.array(["1", "2.0", "hola"])

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype) # < word (4 bytes)

int64
float64
<U4


Además puedes crear un numpy array definirlo de un tipo en concreto. Así, si erróneamente insertar un valor equivocado, no tendrás que preocuparte, ya que obtendrás un `ValueError`

In [52]:
arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype) 

[1 2 3 4]
int32


Pero quiero convertir `arr2` a `integer` para poder mergearlo con `arr`. Para ello, primero tienes que convertir los tipos de ese Numpy Array.

In [60]:
arr2 = np.array([5.0, 6.0])

newarr = arr2.astype(int)

print(arr)
print(newarr.dtype) 
print(np.concatenate((arr, newarr)))

[1 2 3 4]
int64
[1 2 3 4 5 6]


Acabas de usar `concatenate`, una función para mergear arrays en la misma dimensión. Pero ¿qué pasa si quiero mergearlos y aumentar la dimensión? Para ello usamos la función `stack`.

In [68]:
arr = np.array([1, 2], dtype='i')
arr2 = np.array([5.0, 6.0])
newarr = arr2.astype(int)

print(np.stack((arr, newarr)))

[[1 2]
 [5 6]]


Si `stack` detecta que las dimensiones no coinciden, nos lanzará un error.

In [66]:
arr = np.array([1, 2, 3], dtype='i')
arr2 = np.array([5.0, 6.0])

newarr = arr2.astype(int)

try: 
    print(np.stack((arr, newarr)))
except Exception as e:
    print(f"=== ERROR === {e}, arr:{arr.shape}, arr2: {arr2.shape}")

=== ERROR === all input arrays must have the same shape, arr:(3,), arr2: (2,)


## COPY vs VIEW

Mientras que usar **COPY** permite copiar el array en una nueva variable (esto duplicar el array en un nuevo fragmento de memoria independiente al anterior array), **VIEW** permite visualizar y hacer cambios en el propio array usando otra variable. Esto es como un puntero que apunta a la dirección de memoria de un array original. (para más detalles véase [Punteros en C](https://en.cppreference.com/w/c/language/pointer))

In [76]:
arr = np.array([1,2,3,4,5])
print(arr)

x = arr.view()
arr[0] = 42

print(arr)
print(x) 

x[0] = 999

print(x)

[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
[999   2   3   4   5]


In [80]:
arr = np.array([1,2,3,4,5])
print(arr)

x = arr.copy()
arr[0] = 42

print(f"arr: {arr}\nx_copy: {x}")

[1 2 3 4 5]
arr: [42  2  3  4  5]
x_copy: [1 2 3 4 5]


## Search 

Anda, podemos hacer *queries* en estoy arrays. Bueno, sí. Algo parecido...

In [100]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4) # devuelve los índices donde se encuentra dicho valor
print(x) 

(array([3, 5, 6]),)


In [101]:
y = np.where(arr%5 == 0) # mod 5
print(y)

(array([4]),)


Hasta aquí la introducción a Numpy. Ahora vamos a meternos más en materia. A partir de ahora veremos **Numpy aplicado a Estadística**

## Numpy aplicado a estadística