In [2]:
import numpy as np

## Numpy Arrays 

Los arrays de Numpy permiten acceder de manera mucho más óptima (al estar diseñados en C) a contenidos de datos. Además, existen una gran cantidad de operaciones aritméticas y estadísticas `in-built`.

In [8]:
arr = [1,2,3,4,5]
print(f"{arr} --- Type: {type(arr)}")

numpy_arr = np.array(arr)
print(f"{numpy_arr} --- Type: {type(numpy_arr)}")

[1, 2, 3, 4, 5] --- Type: <class 'list'>
[1 2 3 4 5] --- Type: <class 'numpy.ndarray'>


## Dimensiones en Numpy

Numpy permite hacer arrays nestados (al igual que en Python Vanilla), permitiendo crear arrays $n$-dimensionales. ¿Cómo se hace esto?

In [16]:
arr = np.array(42) # 0-Dimensional
print(arr, arr.shape, arr.ndim, "\n")

arr = np.array([1, 2, 3, 4, 5]) # 1-Dimensional
print(arr, arr.shape, arr.ndim, "\n")

arr = np.array([[1,2,3], [4,5,6]]) # 2-Dimensional
print(arr, arr.shape, arr.ndim, "\n") # obtenemos una matriz de tamaño 2 columnas x 3 filas

42 () 0 

[1 2 3 4 5] (5,) 1 

[[1 2 3]
 [4 5 6]] (2, 3) 2 



Podemos forzar la dimensionalidad de un array tal que:

In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


## Acceder a los elementos del array

Al igual que en Python Vanilla, tenemos la posibilidad de acceder a los elementos que conforman un array usando los índices en los que están dispuestos.

En la programación, **el primer índice suele ser el `0`**.

In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(0, 10, 1): # empezamos en cero, acabamos en la pos 9
    print(arr[i]) # imprime el valor de dicha posición

1
2
3
4
5
6
7
8
9
10


In [24]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3]) # devuelve la suma de los elementos en las posiciones 2 y 3

7


### Acceder a arrays $n$-dimensionales